<?php

namespace ContainerI79mCgX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTraitementService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Traitement\Traitement' shared autowired service.
     *
     * @return \App\Traitement\Traitement
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Traitement'.\DIRECTORY_SEPARATOR.'Traitement.php';

        return $container->privates['App\\Traitement\\Traitement'] = new \App\Traitement\Traitement();
    }
}
