<?php

namespace ContainerHr3QzlX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProduitDispoRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\ProduitDispoRepository' shared autowired service.
     *
     * @return \App\Repository\ProduitDispoRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\ProduitDispoRepository'] = new \App\Repository\ProduitDispoRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
