<?php

namespace ContainerSKdhYSa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8O4DYxJService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.8O4DYxJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8O4DYxJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'mouvement' => ['privates', '.errored..service_locator.8O4DYxJ.App\\Entity\\Mouvement', NULL, 'Cannot autowire service ".service_locator.8O4DYxJ": it references class "App\\Entity\\Mouvement" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'mouvement' => 'App\\Entity\\Mouvement',
        ]);
    }
}
