<?php

namespace ContainerSKdhYSa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMouvementRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\MouvementRepository' shared autowired service.
     *
     * @return \App\Repository\MouvementRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\MouvementRepository'] = new \App\Repository\MouvementRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
