<?php

namespace ContainerSKdhYSa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMonthTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\MonthType' shared autowired service.
     *
     * @return \App\Form\MonthType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\MonthType'] = new \App\Form\MonthType();
    }
}
