<?php

namespace ContainerSKdhYSa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMouvementCrudControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\MouvementCrudController' shared autowired service.
     *
     * @return \App\Controller\MouvementCrudController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\MouvementCrudController'] = $instance = new \App\Controller\MouvementCrudController();

        $instance->setContainer(($container->privates['.service_locator.mx0UMmY'] ?? $container->load('get_ServiceLocator_Mx0UMmYService'))->withContext('App\\Controller\\MouvementCrudController', $container));

        return $instance;
    }
}
