<?php

namespace ContainerSKdhYSa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderSortieRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\OrderSortieRepository' shared autowired service.
     *
     * @return \App\Repository\OrderSortieRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\OrderSortieRepository'] = new \App\Repository\OrderSortieRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
