<?php

namespace ContainerSKdhYSa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderTypesRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\OrderTypesRepository' shared autowired service.
     *
     * @return \App\Repository\OrderTypesRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\OrderTypesRepository'] = new \App\Repository\OrderTypesRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
