<?php

namespace ContainerSKdhYSa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTraitementService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Traitement\Traitement' shared autowired service.
     *
     * @return \App\Traitement\Traitement
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Traitement\\Traitement'] = new \App\Traitement\Traitement();
    }
}
