<?php

namespace ContainerVSVNix3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMouvement2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.l45KXOv.App\Entity\Mouvement' shared service.
     *
     * @return \App\Entity\Mouvement
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.l45KXOv": it references class "App\\Entity\\Mouvement" but no such service exists.');
    }
}
