<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9TfT7fc\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9TfT7fc/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9TfT7fc.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9TfT7fc\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container9TfT7fc\App_KernelDevDebugContainer([
    'container.build_hash' => '9TfT7fc',
    'container.build_id' => '1a836dd5',
    'container.build_time' => 1652437925,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9TfT7fc');
