<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVs59ZgM\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVs59ZgM/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVs59ZgM.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVs59ZgM\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVs59ZgM\App_KernelDevDebugContainer([
    'container.build_hash' => 'Vs59ZgM',
    'container.build_id' => '02ef31f8',
    'container.build_time' => 1652267148,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVs59ZgM');
