<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLJsmxlW\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLJsmxlW/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLJsmxlW.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLJsmxlW\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLJsmxlW\App_KernelDevDebugContainer([
    'container.build_hash' => 'LJsmxlW',
    'container.build_id' => '3b7ea5ca',
    'container.build_time' => 1652295099,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLJsmxlW');
