<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.15cd3502.js',
                '/build/vendors-node_modules_fortawesome_fontawesome-free_js_all_js-node_modules_symfony_stimulus-bri-a26026.0e102c73.js',
                '/build/app.11b6f5ad.js',
            ],
            'css' => [
                '/build/app.cb863e9f.css',
            ],
        ],
    ],
],

]];
