<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Situation extends \App\Entity\Situation implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Situation' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Situation' . "\0" . 'produit', '' . "\0" . 'App\\Entity\\Situation' . "\0" . 'ordre', '' . "\0" . 'App\\Entity\\Situation' . "\0" . 'categorie', '' . "\0" . 'App\\Entity\\Situation' . "\0" . 'nombrePlanche', '' . "\0" . 'App\\Entity\\Situation' . "\0" . 'valeurFaciale', '' . "\0" . 'App\\Entity\\Situation' . "\0" . 'prixDeVente', '' . "\0" . 'App\\Entity\\Situation' . "\0" . 'themes', '' . "\0" . 'App\\Entity\\Situation' . "\0" . 'anneeEmission', '' . "\0" . 'App\\Entity\\Situation' . "\0" . 'numero', '' . "\0" . 'App\\Entity\\Situation' . "\0" . 'nature', '' . "\0" . 'App\\Entity\\Situation' . "\0" . 'coteEmission'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Situation' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Situation' . "\0" . 'produit', '' . "\0" . 'App\\Entity\\Situation' . "\0" . 'ordre', '' . "\0" . 'App\\Entity\\Situation' . "\0" . 'categorie', '' . "\0" . 'App\\Entity\\Situation' . "\0" . 'nombrePlanche', '' . "\0" . 'App\\Entity\\Situation' . "\0" . 'valeurFaciale', '' . "\0" . 'App\\Entity\\Situation' . "\0" . 'prixDeVente', '' . "\0" . 'App\\Entity\\Situation' . "\0" . 'themes', '' . "\0" . 'App\\Entity\\Situation' . "\0" . 'anneeEmission', '' . "\0" . 'App\\Entity\\Situation' . "\0" . 'numero', '' . "\0" . 'App\\Entity\\Situation' . "\0" . 'nature', '' . "\0" . 'App\\Entity\\Situation' . "\0" . 'coteEmission'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Situation $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getProduit(): ?\App\Entity\Produits
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProduit', []);

        return parent::getProduit();
    }

    /**
     * {@inheritDoc}
     */
    public function setProduit(?\App\Entity\Produits $produit): \App\Entity\Situation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProduit', [$produit]);

        return parent::setProduit($produit);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrdre(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrdre', []);

        return parent::getOrdre();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrdre(int $ordre): \App\Entity\Situation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrdre', [$ordre]);

        return parent::setOrdre($ordre);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategorie(): ?\App\Entity\Categorie
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategorie', []);

        return parent::getCategorie();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategorie(?\App\Entity\Categorie $categorie): \App\Entity\Situation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategorie', [$categorie]);

        return parent::setCategorie($categorie);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombrePlanche(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombrePlanche', []);

        return parent::getNombrePlanche();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombrePlanche(int $nombrePlanche): \App\Entity\Situation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombrePlanche', [$nombrePlanche]);

        return parent::setNombrePlanche($nombrePlanche);
    }

    /**
     * {@inheritDoc}
     */
    public function getValeurFaciale(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValeurFaciale', []);

        return parent::getValeurFaciale();
    }

    /**
     * {@inheritDoc}
     */
    public function setValeurFaciale(float $valeurFaciale): \App\Entity\Situation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValeurFaciale', [$valeurFaciale]);

        return parent::setValeurFaciale($valeurFaciale);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrixDeVente(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrixDeVente', []);

        return parent::getPrixDeVente();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrixDeVente(float $prixDeVente): \App\Entity\Situation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrixDeVente', [$prixDeVente]);

        return parent::setPrixDeVente($prixDeVente);
    }

    /**
     * {@inheritDoc}
     */
    public function getThemes(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getThemes', []);

        return parent::getThemes();
    }

    /**
     * {@inheritDoc}
     */
    public function setThemes(?string $themes): \App\Entity\Situation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setThemes', [$themes]);

        return parent::setThemes($themes);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnneeEmission(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnneeEmission', []);

        return parent::getAnneeEmission();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnneeEmission(?\DateTimeInterface $anneeEmission): \App\Entity\Situation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnneeEmission', [$anneeEmission]);

        return parent::setAnneeEmission($anneeEmission);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumero(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumero', []);

        return parent::getNumero();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumero(?int $numero): \App\Entity\Situation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumero', [$numero]);

        return parent::setNumero($numero);
    }

    /**
     * {@inheritDoc}
     */
    public function getNature(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNature', []);

        return parent::getNature();
    }

    /**
     * {@inheritDoc}
     */
    public function setNature(?string $nature): \App\Entity\Situation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNature', [$nature]);

        return parent::setNature($nature);
    }

    /**
     * {@inheritDoc}
     */
    public function getCoteEmission(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoteEmission', []);

        return parent::getCoteEmission();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoteEmission(?string $coteEmission): \App\Entity\Situation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoteEmission', [$coteEmission]);

        return parent::setCoteEmission($coteEmission);
    }

}
